### PR TITLE
feat: render templates during CI

### PR DESCRIPTION
**Pull request by giuscri**

### CODE REVIEW

**Comment by edubacco** [comment]
Intresting, but I'm thinking to a fact: when i develop charts, in the default values I let things "disabled" wherever I can.
This means that rendering the chart without custom values, probably hides most of his manifests.

So my doubt is, it's useful to visualize partial manifests?

**Comment by giuscri** [comment]
It catches some issues: better than nothing :)

**Review by edubacco — APPROVED** [review]

**Comment by giuscri** [comment]
Why you think it's not our responsibility to check whether charts render _at least_ with the default values?

**Comment by giuscri** [comment]
Isn't that the same being OK with a library that doesn't run tests because software importing the library is the one ultimately responsible?

**Comment by giuscri** [comment]
We can expect people (including our future selves) to behave like us.

+1 for sending output to /dev/null

**Pull request merged**
